/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/medida.glb -T 
Files: public/models/medida.glb [9.26MB] > C:\Users\andre\Downloads\casa3d\gsap_macbook_landing-main\gsap_macbook_landing-main\public\models\medida-transformed.glb [621.56KB] (93%)
*/

import React, {useEffect} from 'react'
import {useGLTF} from '@react-three/drei'
import useMacbookStore from "../../../store";
import {noChangeParts} from "../../../constants/index.js";
import {Color} from "three";

export default function CasaModel(props) {
    const { color } = useMacbookStore();
    const { nodes, materials, scene } = useGLTF('/models/medida-transformed.glb')

    useEffect(() => {
        scene.traverse((child) => {
            if (child.isMesh) {
                if (!noChangeParts.includes(child.name)) {
                    child.material.color = new Color(color);
                }
            }
        });
    }, [color, scene]);

    return (
        <group {...props} dispose={null}>
            <group position={[12.756, 11.62, -12.521]} rotation={[0, -Math.PI / 2, 0]} scale={[9.509, 6.589, 7.456]}>
                <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
                <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.022']} />
                <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.024']} />
                <mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.025']} />
                <mesh geometry={nodes.Cube005_4.geometry} material={materials['Material.057']} />
                <mesh geometry={nodes.Cube005_5.geometry} material={materials['Material.026']} />
                <mesh geometry={nodes.Cube005_6.geometry} material={materials['Material.085']} />
                <mesh geometry={nodes.Cube005_7.geometry} material={materials['Material.097']} />
                <mesh geometry={nodes.Cube005_8.geometry} material={materials['Material.098']} />
                <mesh geometry={nodes.Cube005_9.geometry} material={materials['Material.099']} />
                <mesh geometry={nodes.Cube005_10.geometry} material={materials['Material.199']} />
                <mesh geometry={nodes.Cube005_11.geometry} material={materials['Material.200']} />
                <mesh geometry={nodes.Cube005_12.geometry} material={materials['Material.379']} />
                <mesh geometry={nodes.Cube005_13.geometry} material={materials['Material.469']} />
                <mesh geometry={nodes.Cube005_14.geometry} material={materials['Material.559']} />
                <mesh geometry={nodes.Cube005_15.geometry} material={materials.PaletteMaterial002} />
                <mesh geometry={nodes.Cube005_16.geometry} material={materials.PaletteMaterial003} />
                <mesh geometry={nodes.Cube005_17.geometry} material={materials.PaletteMaterial001} />
                <mesh geometry={nodes.Cube005_18.geometry} material={materials['Material.051']} />
                <mesh geometry={nodes.Cube005_19.geometry} material={materials['Material.087']} />
                <mesh geometry={nodes.Cube005_20.geometry} material={materials['Material.054']} />
                <mesh geometry={nodes.Cube005_21.geometry} material={materials['Material.028']} />
                <mesh geometry={nodes.Cube005_22.geometry} material={materials['Material.096']} />
            </group>
        </group>
    )
}

useGLTF.preload('/models/medida-transformed.glb')